ALTER TABLE vendors
  ADD COLUMN IF NOT EXISTS wallet_type TEXT NOT NULL DEFAULT 'PHONE';

ALTER TABLE vendors
  ADD COLUMN IF NOT EXISTS mpesa_identifier TEXT;

ALTER TABLE vendors
  ADD COLUMN IF NOT EXISTS account_reference TEXT;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS collected_amount NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS delivery_fee_kes NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS distribution_status TEXT NOT NULL DEFAULT 'NOT_STARTED';
